//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from UFox16ASM.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="UFox16ASMParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IUFox16ASMListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.assembly"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssembly([NotNull] UFox16ASMParser.AssemblyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.assembly"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssembly([NotNull] UFox16ASMParser.AssemblyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] UFox16ASMParser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] UFox16ASMParser.LineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabel([NotNull] UFox16ASMParser.LabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabel([NotNull] UFox16ASMParser.LabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruction([NotNull] UFox16ASMParser.InstructionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruction([NotNull] UFox16ASMParser.InstructionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDirective([NotNull] UFox16ASMParser.DirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDirective([NotNull] UFox16ASMParser.DirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComment([NotNull] UFox16ASMParser.CommentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComment([NotNull] UFox16ASMParser.CommentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.jump"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJump([NotNull] UFox16ASMParser.JumpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.jump"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJump([NotNull] UFox16ASMParser.JumpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.cmp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmp([NotNull] UFox16ASMParser.CmpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.cmp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmp([NotNull] UFox16ASMParser.CmpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.mov"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMov([NotNull] UFox16ASMParser.MovContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.mov"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMov([NotNull] UFox16ASMParser.MovContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.arithmetic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArithmetic([NotNull] UFox16ASMParser.ArithmeticContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.arithmetic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArithmetic([NotNull] UFox16ASMParser.ArithmeticContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.bitshift"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitshift([NotNull] UFox16ASMParser.BitshiftContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.bitshift"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitshift([NotNull] UFox16ASMParser.BitshiftContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.logic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogic([NotNull] UFox16ASMParser.LogicContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.logic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogic([NotNull] UFox16ASMParser.LogicContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.basic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBasic([NotNull] UFox16ASMParser.BasicContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.basic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBasic([NotNull] UFox16ASMParser.BasicContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.operand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperand([NotNull] UFox16ASMParser.OperandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.operand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperand([NotNull] UFox16ASMParser.OperandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant([NotNull] UFox16ASMParser.ConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant([NotNull] UFox16ASMParser.ConstantContext context);
}
