//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from UFox16ASM.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IUFox16ASMListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class UFox16ASMBaseListener : IUFox16ASMListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.assembly"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssembly([NotNull] UFox16ASMParser.AssemblyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.assembly"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssembly([NotNull] UFox16ASMParser.AssemblyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLine([NotNull] UFox16ASMParser.LineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLine([NotNull] UFox16ASMParser.LineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabel([NotNull] UFox16ASMParser.LabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabel([NotNull] UFox16ASMParser.LabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruction([NotNull] UFox16ASMParser.InstructionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruction([NotNull] UFox16ASMParser.InstructionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirective([NotNull] UFox16ASMParser.DirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirective([NotNull] UFox16ASMParser.DirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComment([NotNull] UFox16ASMParser.CommentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComment([NotNull] UFox16ASMParser.CommentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.jump"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJump([NotNull] UFox16ASMParser.JumpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.jump"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJump([NotNull] UFox16ASMParser.JumpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.cmp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmp([NotNull] UFox16ASMParser.CmpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.cmp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmp([NotNull] UFox16ASMParser.CmpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.mov"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMov([NotNull] UFox16ASMParser.MovContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.mov"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMov([NotNull] UFox16ASMParser.MovContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.arithmetic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArithmetic([NotNull] UFox16ASMParser.ArithmeticContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.arithmetic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArithmetic([NotNull] UFox16ASMParser.ArithmeticContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.bitshift"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBitshift([NotNull] UFox16ASMParser.BitshiftContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.bitshift"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBitshift([NotNull] UFox16ASMParser.BitshiftContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.logic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogic([NotNull] UFox16ASMParser.LogicContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.logic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogic([NotNull] UFox16ASMParser.LogicContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.basic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBasic([NotNull] UFox16ASMParser.BasicContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.basic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBasic([NotNull] UFox16ASMParser.BasicContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.operand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperand([NotNull] UFox16ASMParser.OperandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.operand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperand([NotNull] UFox16ASMParser.OperandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UFox16ASMParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstant([NotNull] UFox16ASMParser.ConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UFox16ASMParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstant([NotNull] UFox16ASMParser.ConstantContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
